### ISSUE TITLE
Fluxnews images loading error

### ISSUE THREAD

**Issue by lfabiotargino** [inspireui/fluxbuilder#122]
Hi,

My JSON Content request is working fine ( https://www.pbagora.com.br/wp-json/wp/v2/posts ) and i can request the content Fluxnews and Fluxbuilder, but i have an issue for loading images from my JSON content. As you can see on print screens attached some times the content show the images, but with many contents the image not load. from 

+ Product & version: fluxnews 1.4.1
+ Flutter (or React Native) version:  Flutter (Channel beta, v1.17.0, on Mac OS X 10.14.6 18G4032, locale pt-BR)
+ Testing Device/Simulator: Asus mobile phone device

![Captura de Tela 2020-06-11 às 09 26 40](https://user-images.githubusercontent.com/6508249/84385284-b57d0d80-abc5-11ea-98f1-610514fdf189.png)
![Captura de Tela 2020-06-11 às 09 26 09](https://user-images.githubusercontent.com/6508249/84385295-b877fe00-abc5-11ea-8006-c5c0d84fddb3.png)
![Captura de Tela 2020-06-11 às 09 26 02](https://user-images.githubusercontent.com/6508249/84385297-b9109480-abc5-11ea-8c97-bdfb566481a1.png)

**Comment by minhcasi** [comment]
@lfabiotargino - thank you for reporting - we will investigate and let you know

**Comment by dttrung26** [comment]
Hi @lfabiotargino , 
First of all, I deeply apologize for late response. 
In your case, it seems like this issue comes from the lack of several necessary plugins in your site. Please make sure that `Better REST API Featured Images` and `Regenerate Thumbnails` latest version are installed and enabled. Don't forget to run "Regenerate Thumbnails for Attachments" to make sure all of your set up are correct. 
Let me know if you still have any question. 
Best!

**Comment by dttrung26** [comment]
Closed due to no response from customer. 
Feel free to reopen this ticket if you are still experience this issue!
Best!
