### ISSUE TITLE
fluxbuilder.exe stopped working - Windows 7 64bit

### ISSUE THREAD

**Issue by akashsharnarthi** [inspireui/fluxbuilder#160]
Screenshot of the error: https://prnt.sc/tkrket
I have tried flux builder in my other Windows OS PC too, I am getting the same error. 
 
but its working fine in macOS (tried in a friend laptop).
requesting you to please check and resolve ASAP!

**Comment by minhcasi** [comment]
@akashsharnarthi - the Fluxbuilder is only working on window +10 64bit - it will not work on window 7 or Vista (as we build it base on Flutter framework so that there is the version limitation) - you could check the download package from latest version https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.6

**Comment by akashsharnarthi** [comment]
Thanks for the clarification. And iam having some issues regarding Fluxtore
eCommerce app.
Can I ask here of should I have create new?

**Comment by minhcasi** [comment]
@akashsharnarthi - pls help to create on this link http://github.com/inspireui/support/issues - thank you!
