### ISSUE TITLE
link a banner image to product, tab and screen  in flux builder

### ISSUE THREAD

**Issue by nucl123** [inspireui/fluxbuilder#167]
Hi,
How can we link a banner image to product, tab and screen  in flux builder?
Is it by product id, link, or name? and the screen names?
Had tried with all these, none seems to work, please let us know.

![image](https://user-images.githubusercontent.com/51371138/88878982-d232da80-d231-11ea-842a-6cb78ee3cc0d.png)

**Comment by philipvu30** [comment]
Hi,

1. For Product -> type in product id (i.e 21).
2. For TAB -> type in one of these options:
- category
- search
- cart
- profile
- wishlist
- blog
- page
- html 
- static
- story
- postScreen
- dynamic
3. For Screen -> type in one of these options:
- /home-screen
- /home
- /login
- /register
- /products
- /wishlist
- /checkout
- /orders
- /blogs
- /notify
- /category
- /search
4. For URL -> Currently you cannot see the preview of it because webview feature is not supported on Windows and MacOS. The concept is it will open the webview with the URL you provided.
