### ISSUE TITLE
Fluxbuilder not working

### ISSUE THREAD

**Issue by nucl123** [inspireui/fluxbuilder#179]
Hi
The fluxbuilder is not working, have tried to re install, also checked with mac and windows version, its all showing same issue, the product page is stuck at loading, How to fix it? Is there any server issue?
![image](https://user-images.githubusercontent.com/51371138/89716384-2a49a980-d9b5-11ea-94bd-bef31bb163ed.png)

**Comment by minhcasi** [comment]
@nucl123 - I've forwarded to the team to invest this issue and will let you know - would you mind to share the login access of the Fluxbuilder to inspireui.team@gmail.com - we may need some debug on your account. It's working with our testing with some other accounts.

**Comment by AJOnlineServices** [comment]
I'm having the exact same issue.
Also, I notice that no links on the program actually work (click the news articles on the right hand side, and then try clicking the blue links - none open).
It also appears that the 'Settings' button above the iPad button does absolutely nothing, and the 'Save' button below that does nothing but just turns to some sort of 'loading' animation.
Also, uploading any images in the builder form the PC or from the store website results in the program showing the 'loading' animation and does not make or save any of the changes.
Are we able to maybe downgrade the program to an earlier version to see if that helps?

**Comment by nucl123** [comment]
> @nucl123 - I've forwarded to the team to invest this issue and will let you know - would you mind to share the login access of the Fluxbuilder to [inspireui.team@gmail.com](mailto:inspireui.team@gmail.com) - we may need some debug on your account. It's working with our testing with some other accounts.

@minhcasi Hi, we had emailed you the password, it does not look like account specific issue, we had tried to register a new account and then login also, having same issue. 
**Please fix it ASAP, note that, we had purchased both of your products, fluxstore pro and fluxstore prestashop, unable to use it, not even able to use fluxbuilder now!, waiting for a quick solution.**

**Comment by AJOnlineServices** [comment]
I'm hoping that you are able to resolve this **today**, otherwise I'll be filling a refund request with Envato for our licences we have just purchased as the product clearly does not work as intended.

Does anybody know how quick Envato issue refunds, because if its more than 2 days it'll be quicker for me to claim a Section 75 with my card issuer and have them refund directly

**Comment by AJOnlineServices** [comment]
I see you have deleted my comment requesting a refund on the fault product. Not cool.
Refund has now been issued but for only one of the licences. Now that it has been refunded, I should not have any issues having the rest refunded which I'll now submit to Envato.
In the meantime, if you ever do actually fix the issues, I would be more than happy to repurchase the licences.
You appear to have a good product, which only almost works.
However, your customer service and support are terribly shocking and should be worked on instead of lying to people and ignoring them consistently.

**Comment by minhcasi** [comment]
@nucl123 - please use the latest release - we have fixed the issue - https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.7 - thank you!
