### ISSUE TITLE
can't  open builder in win10

### ISSUE THREAD

**Issue by trunghieuvn** [inspireui/fluxbuilder#4]
![picturemessage_1tlrmqx0 qsf](https://user-images.githubusercontent.com/19247680/76160421-cea49700-615c-11ea-9bd6-86e5824e2098.png)

**Comment by trunghieuvn** [comment]
please add .dll to folder Fluxbuilder.exe
https://www.dll-files.com/vcruntime140_1.dll.html

**Comment by sonumas007** [comment]
I have found the solution instead of pasting to system 32 once must paste to the builder folder itself even I will suggest to you to add vcruntime140_1.dll in your package

Thanks

**Comment by sonumas007** [comment]
okay so now my questions are
1) How to use any shortcode of WordPress or woo commerce in our application via flux-builder.
2) If we have to add more links or pages under profile where to edit those as flux-builder do not support the page to edit its just call the profile page.
3) How to add the page on the left side menu of the app as there are only shop, blog and calling all category where we dont need catergory to be called on left side but we need to give one page link so that people can navigate to that page.

Thanks
