### ISSUE TITLE
Problem Using Builder

### ISSUE THREAD

**Issue by bikostudio** [inspireui/fluxbuilder#67]
Hi @minhcasi 
I have activated my License on builder with the URL of my site. Now after downloaded the latest version when I try to download the JASON file I got this error.

![2020-05-08_163346](https://user-images.githubusercontent.com/62074493/81416566-2c982f80-914a-11ea-9435-a5162b841932.jpg)

Thank you

**Comment by bikostudio** [comment]
@minhcasi  Also the Version of lastest downloadable package is 1.0.3  not 1.0.4
Please check

![2020-05-08_164053](https://user-images.githubusercontent.com/62074493/81417074-eb544f80-914a-11ea-882c-191272bf00fc.jpg)

Thank you

**Comment by nagri297** [comment]
Same issue with me as well. The version is the same old version.

**Comment by dttrung26** [comment]
Hi @bikostudio , please pay attention to your previous site url which has a " / " at the end while your current one has not. Please edit, try again and kindly confirm if it works. Otherwise, I'll give further assistance. @nagri297 could you please take a look to see if this is your case as well mate. Many thanks.

**Comment by dttrung26** [comment]
Close due to unactivity from user. Feel free to reopen this ticket again if you still are facing this issue. 
Many thanks!
