### ISSUE TITLE
Fluxstore builder is not opening internal file manager at system & Not Loading site images also

### ISSUE THREAD

**Issue by deepusodhi11** [inspireui/fluxbuilder#76]
Hi recently today i purchased your application it is good but i m getting some issues and query please help and explain

Issue :
1. When i go to change flux builder change logo, category or home page image is not open system manager 

![image](https://user-images.githubusercontent.com/65160811/81586044-9fb3d700-93d2-11ea-9abe-f29a81b41642.png)
2. Then i thought used site uploader but its not loading images its only spinning i wait for last 30 min but still same issued only spin no image loading
![image](https://user-images.githubusercontent.com/65160811/81586198-cb36c180-93d2-11ea-9957-484072777ba0.png)
3. In Category Sub Category is not showing ? We have added subcategory also
4. About Images images alignment is also not good some images showing small some big 
![image](https://user-images.githubusercontent.com/65160811/81586559-4c8e5400-93d3-11ea-930d-4e4bb0ab7db7.png)

Query:
1. I want to change daily home page images can i change without update the app through wordpress plugin or where ?
2. Is there having geo location products can be show through geo location
3. If you updated the app the how we can do this without loosing old data 
4. is there having mltivendor option?

**Comment by minhcasi** [comment]
@deepusodhi11 - thank you for the feedbacks, we will investigate these question and will get back you later

**Comment by deepusodhi11** [comment]
when u didn't see my issues also??

**Comment by vumanhsn97** [comment]
1. Fixed in windows. Download again
2. Fixed in next version
3. Your category is empty. Please add one or more products
4. Image auto fix by width. You can fix height in lib/common/tools.dart https://tppr.me/SuJdv
 - home page: you can use cache. Follow this document: https://docs.inspireui.com/fluxstore/performance/
- geo location: future request
- updated: Just copy config.json file
- vendor product: https://1.envato.market/NW4q1
