### ISSUE TITLE
Unable to install fluxbuilder windows 7Sp1

### ISSUE THREAD

**Issue by Shadowji** [inspireui/fluxbuilder#84]
I tried to install fluxbuilder on different operating system. Made the fresh installation of windows 7 64bit to my system and installed vcredist_64.exe tried to open flux builder and got this error" A PROBLEM HAS STOPPED THE PROGRAM. Please CLOSE THE PROGRAM"
![IMG-20200523-WA0004](https://user-images.githubusercontent.com/65677660/82716412-ed72ee00-9cb4-11ea-867a-f7117c466d53.jpg)

**Comment by minhcasi** [comment]
@Shadowji - we have not tested on window 7, but on window +8, it is working fine. 

I've reported to the technical team to try on win7 and let you know - thank you!

**Comment by dttrung26** [comment]
Hi @Shadowji , 

I've been researching some similar cases which had problem in windows 7 like yours. It turns out that Flutter don't support Win7 at the moment. Please take a look at those win7 issues ticket on Flutter for reference: https://github.com/flutter/flutter/issues/40749, https://github.com/flutter/flutter/issues/40855. 
Moreover, I think it's much better to switch to Windows higher version because Windows 7 hasn't been supported since January this year. 
Let me know if you still have any questions.

Have a nice day,
Trung.

**Comment by Sunbreak** [comment]
After taking look at https://github.com/flutter/flutter/issues/40749 and trying, I'm convinced that `Flutter for Windows works on Win7Sp1-x64 with MSVC runtimes installed`

Maybe missing `Service Pack 1`, `x64` or `MSVC runtimes` is the cause
